# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blogs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blogs
	pod 'FirebaseUI/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  target 'BlogsTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'BlogsUITests' do
    # Pods for testing
  end

end
